### ISSUE TITLE
上传成功后文字修改

### ISSUE THREAD

**Issue by onedou** [tatfook/keepnote#1]
恭喜！
http://keepwork.com/liyu/notes/liyu_20171215_151723(这个加上url，点击浏览器打开)
已成功上传。
[打开文件（浏览器打开url）][确定（跟现在的确定一样）]

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/34244959-c9e4be92-e662-11e7-8826-329deeb6276a.png)

**Comment by Sandu1213** [comment]
暂时无法验证，稍后再看

**Comment by onedou** [comment]
This problem is too long. I shut it down first.

**Comment by onedou** [comment]
This issue is too long. I shut it down first.
