### ISSUE TITLE
参与网站没有正常显示

### ISSUE THREAD

**Issue by onedou** [tatfook/keepnote#4]
选择站点 参与网站没有正常显示

**Comment by Sandu1213** [comment]
Android手机上效果：
- 参与网站还是显示的不对
![image](https://user-images.githubusercontent.com/21214285/34246221-9193690c-e668-11e7-9a13-c093952e24a2.png)
-  编辑页
![image](https://user-images.githubusercontent.com/21214285/34246416-77eb0c2a-e669-11e7-9a87-0969f9f908e7.png)

IOS手机上效果：
-  没有显示参与网站的信息
![image](https://user-images.githubusercontent.com/21214285/34246459-aa575b82-e669-11e7-903b-92dafa96a792.png)
- 编辑器里语法没有高亮显示
![image](https://user-images.githubusercontent.com/21214285/34246716-aeb2f316-e66a-11e7-84fb-f46d0d8c8657.png)

**其他问题：**  
1.登录成功后，页面会刷新2次   
2.我的网站列表里数据出来过慢    
![image](https://user-images.githubusercontent.com/21214285/34246893-6e02987a-e66b-11e7-8b31-c1d616b4f4d1.png)

3.如果直接点击注册了，就卡着不能用了（IOS）  
![image](https://user-images.githubusercontent.com/21214285/34246878-60c88cd2-e66b-11e7-89e3-9366252e3223.png)

4.页面编辑器里，编写后如何保存和返回  
5.录音，上传文件，# 功能不可用
6.拍照的图片看不到

**Comment by onedou** [comment]
1.登录成功后，页面会刷新2次 #7
2.我的网站列表里数据出来过慢 #8
3.如果直接点击注册了，就卡着不能用了（IOS）#9
4.页面编辑器里，编写后如何保存和返回 (需要原型设计？)
5.录音(#10)，上传文件(android可用，ios需自行设计UI)，#功能不可用  (排查)
6.拍照的图片看不到(需确定上传图片路径)

**Comment by onedou** [comment]
This issue is too long. I shut it down first.
