### ISSUE TITLE
APP名字更改

### ISSUE THREAD

**Issue by onedou** [tatfook/keepnote#5]
这个项目桌面Icon文字叫KeepWork助手 吧
或者就是keepwork

**Comment by onedou** [comment]
![image](https://user-images.githubusercontent.com/3422640/34245395-aba69214-e664-11e7-9649-ae6b232a0a58.png)

**Comment by Sandu1213** [comment]
暂时无法验证，待后续安装正式的ipa或者apk时再查看

**Comment by onedou** [comment]
This issue is too long. I shut it down first.
